import {
    createIcons,
    Menu,
    ArrowRight,
    Globe,
    House,
    PanelLeft,
    ChevronUp,
    ChevronDown,
    Calendar,
    MessageCircle,
    Bell,
    LogOut,
    CircleUser,
    Sparkles,
    CircleArrowRight,
    Heart,
    Link,
    Share2,
    MousePointer2,
    Circle,
    Share,
    SquarePen,
    ImageUp,
    Instagram,
    Linkedin,
    Twitter,
    Facebook,
    Plus,
    Settings,
    PartyPopper,
    MessageSquareQuote,
    Orbit,
    Users,
    Building2,
    Files,
    Award,
    Clock,
    ShieldCheck,
    Megaphone,
    Handshake,
    Ban,
    Tractor,
    Timer,
    Search,
    MapPin,
    Star,
    UserPlus,
    Navigation,
    FileClock,
    Mail,
    Contact,
    BookOpenText,
    CalendarDays,
    Info,
    Crosshair,
    Loader,
    RefreshCw

} from 'lucide';

function registerIcons() {
    createIcons({
        icons: {
            Menu,
            ArrowRight,
            Globe,
            House,
            PanelLeft,
            ChevronUp,
            ChevronDown,
            Calendar,
            MessageCircle,
            Bell,
            LogOut,
            CircleUser,
            Sparkles,
            CircleArrowRight,
            Heart,
            Link,
            Share2,
            MousePointer2,
            Circle,
            Share,
            SquarePen,
            ImageUp,
            Search,
            Instagram,
            Linkedin,
            Twitter,
            Facebook,
            Plus,
            Settings,
            PartyPopper,
            MessageSquareQuote,
            Orbit,
            Users,
            Building2,
            Files,
            Award,
            Clock,
            Megaphone,
            Handshake,
            Ban,
            Tractor,
            Timer,
            ShieldCheck,
            MapPin,
            Star,
            UserPlus,
            Navigation,
            FileClock,
            Mail,
            Contact,
            BookOpenText,
            CalendarDays,
            Info,
            Crosshair,
            Loader,
            RefreshCw

        }
    });
}

document.addEventListener('livewire:navigated', () => {
    registerIcons()
})

document.addEventListener('DOMContentLoaded', () => {
    registerIcons()
})


Livewire.hook('morph.added',  ({ el }) => {
    registerIcons()
})
