apiVersion: v1
kind: Secret
metadata:
  namespace: smile-app
  name: digitalocean-secrets
data:
  access-token: "ZG9wX3YxXzU4ZjU0YjBjYzhlMGU2ZWZkY2JjNDBiYTBmNDBkMjQ0MmQwYjI2N2ZkMzdhYWE4NzYyMDYxMGUxMWZkYmMwZDI="


#  dop_v1_58f54b0cc8e0e6efdcbc40ba0f40d2442d0b267fd37aaa87620610e11fdbc0d2
