apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smile-app-storage-pvc
  namespace: smile-app
  labels:
    app: smile-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage  # DigitalOcean's block storage class